### ISSUE TITLE
Poggers

### ISSUE THREAD

**Issue by WillTheDeveloper** [WillTheDeveloper/OctoNet#1]

**Comment by hrszpuk** [comment]
So it's like an API wrapper or more like GitHub CLI?

**Comment by WillTheDeveloper** [comment]
Lol, this issue was created using the application

**Comment by WillTheDeveloper** [comment]
> So it's like an API wrapper or more like GitHub CLI? @WillTheDeveloper ?
> 

Api Wrapper :) @hrszpuk

**Comment by hrszpuk** [comment]
Ah okay... Would be cool to make an application that did something similar to GitHub CLI but with improvements.

**Comment by hrszpuk** [comment]
Like GitHub CLI is purely focused on GitHub and not Git which makes some stuff feel really weird. Would like to see a tool that is a mix of both. Maybe I'll look into it. 

Anyway, it's pretty cool how you created an issue with your own API wrapper 👍🏼

**Comment by WillTheDeveloper** [comment]
Yeah. I don't know if you noticed but I did the same with a discord bot, an API wrapper that you can interact with but was written in JS. I'll also look into that.
